apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
  labels:
    app: product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: product
        image: kidharb/product
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: database
        env:
        - name: NODE_ENV
          value: "production"
        - name: POSTGRES_HOST
          value: "psql-service"

